Drop Iosevka submodule, causes isses
error: Server does not allow request for unadvertised object 62eb8787bb41038647d9a6ded5ec2b1d5f30de49
Fetched in submodule path 'Iosevka', but it did not contain 62eb8787bb41038647d9a6ded5ec2b1d5f30de49. Direct fetching of that commit failed.